# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:4

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - bower_components/
  - node_modules/

stages:
  - build
  - test
  - deploy

before_scripts:
  - npm install bower gulp

build_web:
  stage: build
  script:
    - bower install
    - npm install
    - npm run build

test:
  stage: test
  script:
    - npm run test

deploy_testing:
  stage: deploy
  script:
    - ./deploy.sh
  environment:
    name: testing
    url: http://accessimap-editeur-der-testing.surge.sh
  when: manual
  only:
  - master
