language: node_js

node_js:
  - '0.12'

before_install:
  - 'npm i bower grunt-cli'

install:
  - 'gem install compass'
  - 'bower install'

script:
  - 'npm install'
  - 'npm test'

cache:
  directories:
    - node_modules
