language: node_js

node_js:
  - '4.4.2'

before_install:
  - 'npm i bower gulp'

install:
  - 'gem install compass'
  - 'bower install'

script:
  - 'npm install'
  - 'npm test'
  - 'npm run build'

deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master

cache:
  directories:
    - node_modules
