language: node_js

node_js:
  - '4.4.2'

before_install:
  - 'npm i bower gulp'

install:
  - 'gem install compass'
  - 'bower install'

script:
  - 'npm install'
  - 'npm test'
  - 'ls -la'
  - 'mkdir .tmp'
  - 'npm run build'
  - 'ls .tmp -la'
  - 'chmod 700 deploy.sh'

deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true
  on:
    branch: master

cache:
  directories:
    - node_modules
