language: node_js

node_js:
  - '4.4.2'

before_install:
  - 'npm i bower gulp'

install:
  - 'gem install compass'
  - 'bower install'

script:
  - 'npm install'
  - 'npm test'

cache:
  directories:
    - node_modules
